/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ucieffe.kata.goosegame;

import java.io.*;

public class GooseGameApp {

    private final InputChannel inputChannel;
    private final OutputChannel outputChannel;

    public GooseGameApp(InputChannel in, OutputChannel out) {
        inputChannel = in;
        outputChannel = out;
    }

    public void start() {
        while(true) {
            String command = inputChannel.read();
            outputChannel.write(command);
        }
    }

    public static void main(String[] args) {
        InputChannel inputChannel = new SystemInputChannel(new BufferedReader(new InputStreamReader(System.in)));
        OutputChannel outputChannel = new SystemOutputChannel(System.out);
        new GooseGameApp(inputChannel, outputChannel).start();
    }
}
