/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ucieffe.kata.goosegame;

import java.io.*;

public class GooseGame {

    private final CommandFactory commandFactory;
    private final OutputEventListener outputListener;

    public GooseGame(CommandFactory commandFactory, OutputEventListener outputListener) {
        this.commandFactory = commandFactory;
        this.outputListener = outputListener;
    }

    public void nextCommand(String stringCommand) {
        GooseGameCommand command = commandFactory.chainOfCommands();
        GooseGameEvent event = command.handle(stringCommand);
        outputListener.receive(event);
    }

    @SuppressWarnings("InfiniteLoopStatement")
    public static void main(String[] args) {
        InputChannel inputChannel = new SystemInputChannel(new BufferedReader(new InputStreamReader(System.in)));
        OutputChannel outputChannel = new SystemOutputChannel(System.out);
        OutputStreamEventListener listener = new OutputStreamEventListener(outputChannel);
        Board board = new Board();
        CommandFactory commandFactory = new CommandFactory(board);
        GooseGame gooseGame = new GooseGame(commandFactory, listener);
        do {
            String command = inputChannel.read();
            gooseGame.nextCommand(command);
        } while (true);
    }
}
