/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ucieffe.kata.goosegame;

import java.io.*;

public class GooseGame {

    private final CommandInterpreter commandInterpreter;
    private final OutputEventListener outputListener;

    public GooseGame(CommandInterpreter commandInterpreter, OutputEventListener outputListener) {
        this.commandInterpreter = commandInterpreter;
        this.outputListener = outputListener;
    }

    public void nextCommand(String stringCommand) {
        GooseGameCommand command = commandInterpreter.run(stringCommand);
        GooseGameEvent event = command.handle(stringCommand);
        outputListener.receive(event);
    }

    @SuppressWarnings("InfiniteLoopStatement")
    public static void main(String[] args) {
        InputChannel inputChannel = new SystemInputChannel(new BufferedReader(new InputStreamReader(System.in)));
        OutputChannel outputChannel = new SystemOutputChannel(System.out);
        OutputStreamEventListener listener = new OutputStreamEventListener(outputChannel);
        Board board = new Board();
        CommandInterpreter commandInterpreter = new CommandInterpreter(new CommandFactory(board));
        GooseGame gooseGame = new GooseGame(commandInterpreter, listener);
        do {
            String command = inputChannel.read();
            gooseGame.nextCommand(command);
        } while (true);
    }
}
